version: '3.2'
services:
  api-auth:
    build:
      context: .
      dockerfile: 'Dockerfile'
    image: api-auth:latest
    container_name: api-auth
    restart: always
    ports:
      - '3000:3000'